artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/krishnaik06/datasets/raw/refs/heads/main/winequality-data.zip ##our data source
  local_data_file: artifacts/data_ingestion/data.zip ##local data source
  unzip_dir: artifacts/data_ingestion ##dir to saved our unzip file

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv ##data input
  STATUS_FILE: artifacts/data_validation/status.txt ##check if the data validation is true or not


data_transformation:
  root_dir: artifacts/data_transformation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  TRAIN_DATA: artifacts/data_transformation/train.csv
  TEST_DATA: artifacts/data_transformation/test.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_filename: artifacts/model_evaluation/metrics.json





